### ISSUE TITLE
Making a grappling hook

### ISSUE THREAD

**Issue by aldocd4** [gecko0307/dmech#11]
Hello,

I would like to know if I can build a grappling hook system using dmech ? 

Something like the hook in the game [Teeworlds](https://www.youtube.com/watch?v=LfmBjSKGyaA).

thanks

**Comment by gecko0307** [comment]
It's basically a rope, as far as I understand. dmech doesn't have a specialized rope system, but maybe a chain of `BallConstraint`s will work out? Also `DistanceConstraint` can be used to replicate Teeworlds mechanics to some extent, because it can work as a spring.

**Comment by aldocd4** [comment]
Thanks, a chain of BallConstraint is working nicely for a basic rope. I will try to improve this.
