### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by JonathanILevi** [gecko0307/dmech#12]
You claim "fully platform-independent" but you use DLib which does not support MacOS?

**Comment by gecko0307** [comment]
dlib should probably compile under Mac OS, I just don't test it. At least it doesn't strictly depend on anything beyond Posix.

**Comment by JonathanILevi** [comment]
Okay.

I appreciate that.  I got the impression from your post that you purposely disallowed building on MacOS.  I am not a fan of MacOS either but I am not will to cut out that portion of my potential audience. (I guess I am also not a fan of Windows...)  DMech is a viable option for me then.  If I receive failures on MacOS then I will try to submit fixes myself.
