### ISSUE TITLE
Update dmech on DUB? (also update dlib dependency)

### ISSUE THREAD

**Issue by redthing1** [gecko0307/dmech#13]
Hello,

I'd like to use the newer `dlib` functionality, but unfortunately `dmech` is still locked to an older version of `dlib`.

I noticed that there was a [commit](https://github.com/gecko0307/dmech/commit/5abe2510e1d905858628083450f992b33a308a7c) bumping the dlib version to 0.17.

Could you perhaps release a patch version of dmech that updates the dlib dependency? Thanks!

**Comment by gecko0307** [comment]
Sure

**Comment by gecko0307** [comment]
Released 0.4.1

**Comment by redthing1** [comment]
Thank you!
