### ISSUE TITLE
poor performance with many shapes

### ISSUE THREAD

**Issue by redthing1** [gecko0307/dmech#14]
Hi,

`dmech` is a really nice library with an excellent API.

But I've been having some performance trouble when I try running a larger number of shapes in it:

I made a benchmark program to demonstrate the issue: https://github.com/xdrie/dmech_perf_test

With `32` blocks and `2048` max collisions, it is pretty fast:
```
❯ ./dmech_perf_test --col 2048 --blk 32
dmech perf test (2048 max collisions, 32 blocks)
added 32 blocks
running benchmark (600 iterations)
result: 1.135 msec per iteration
```

With `64` blocks and `2048` max collisions, it is still quite fast:
```
❯ ./dmech_perf_test --col 2048 --blk 64
dmech perf test (2048 max collisions, 64 blocks)
added 64 blocks
running benchmark (600 iterations)
result: 2.80667 msec per iteration
```

With `256` blocks and `2048` max collisions, it slows down significantly, this would dip the FPS:
```
dmech perf test (2048 max collisions, 256 blocks)
added 256 blocks
running benchmark (600 iterations)
result: 18.0417 msec per iteration
```

With `512` blocks and `2048` max collisions, I ran the program for 90 seconds and it did not complete.
Anything higher or in that range gives similar results; the program seems to slow down exponentially with big numbers of rigid bodies.
Generally, with any numbers larger than this, the program will run for minutes and minutes, and will max out the CPU core, but will not complete.

**Comment by gecko0307** [comment]
These results are expected, dmech actually is very simple engine with little to no optimizations for large scenes. For example, there's no island management or any other acceleration heuristic, so the simulation cost is always O(N). And of course there's no GPU support, in contrast with popular engines. Not sure if I fix this in foreseeable future, seems this project doesn't have such many interested users. But who knows.

**Comment by redthing1** [comment]
was this changed, or is it a wontfix?

**Comment by gecko0307** [comment]
wonfix. I've decided to switch to third-party physics engine in my projects.

**Comment by redthing1** [comment]
> wonfix. I've decided to switch to third-party physics engine in my projects.

out of curiosity, which physics engine, and is there a D library for it?

**Comment by gecko0307** [comment]
Newton. I wrote a bindbc binding for it: https://github.com/gecko0307/bindbc-newton

**Comment by redthing1** [comment]
Do you perhaps have open source sample/demo code for the library?

**Comment by gecko0307** [comment]
I have, I'm currently working on Newton integration into my graphics engine: https://github.com/gecko0307/dagon-newton. There's a character controller demo.
